SCRAPE_FEATURES = [
    "title",
    "price",
    "property_condition",
    "construction_year",

    "country",
    "province",
    "city",
    "postal_code",
    "street",
    "street_number",
    "distance_to_center",
    "neighborhood_safety",

    "bedrooms",
    "bedroom_1_area",
    "bedroom_2_area",
    "bedroom_3_area",
    "bedroom_4_area",
    "bedroom_5_area",
    "bedroom_6_area",
    "area",
    "livable_area",
    "living_room_area",
    "veranda",
    "veranda_area",
    "attic",
    "attic_area",
    "basement",
    "basement_area",
    "garage",
    "garage_area",
    "number_of_garages",
    "number_of_parking_spaces",
    "furnished",

    "kitchen_area",
    "kitchen_equipment",
    "bathrooms",
    "number_of_shower_cabins",
    "number_of_baths",
    "number_of_toilets",

    "epc",
    "heating_type",
    "glass_type",
    "elevator",
    "wheelchair_accessible",
    "solar_panels",
    "solar_panel_area",

    "number_of_facades",
    "facade_width",
    "floor",
    "number_of_floors",
    "terrace",
    "terrace_area",
    "plot_depth",
    "terrace_front_width",
    "sewer_connection",
    "water_connection",
    "gas_connection",
    "swimming_pool",
    "garden",
    "garden_area",

    "source",
]

APP_FEATURES = [
    "title",
    "price",
    "property_condition",
    "construction_year",

    "country",
    "province",
    "city",
    "postal_code",
    "street",
    "street_number",
    "distance_to_center",
    "neighborhood_safety",

    "bedrooms",
    "bedroom_1_area",
    "bedroom_2_area",
    "bedroom_3_area",
    "bedroom_4_area",
    "bedroom_5_area",
    "bedroom_6_area",
    "area",
    "livable_area",
    "living_room_area",
    "veranda",
    "veranda_area",
    "attic",
    "attic_area",
    "basement",
    "basement_area",
    "garage",
    "garage_area",
    "number_of_garages",
    "number_of_parking_spaces",
    "furnished",

    "kitchen_area",
    "kitchen_equipment",
    "bathrooms",
    "number_of_shower_cabins",
    "number_of_baths",
    "number_of_toilets",

    "epc",
    "heating_type",
    "glass_type",
    "elevator",
    "wheelchair_accessible",
    "solar_panels",
    "solar_panel_area",

    "number_of_facades",
    "facade_width",
    "floor",
    "number_of_floors",
    "terrace",
    "terrace_area",
    "plot_depth",
    "terrace_front_width",
    "sewer_connection",
    "water_connection",
    "gas_connection",
    "swimming_pool",
    "garden",
    "garden_area",

    "source",
]